### ISSUE TITLE
Cant import

### ISSUE THREAD

**Issue by mandelmonkey** [makehumancommunity/community-plugins-maketarget#3]
Hi I have blender 2.8.0 on windows and the MakeHuman plugin working, however I dont have much luck with the maketarget
I have tried installing the addon that came with MakeHuman 1.20 and I get a warning that I need to use blender version 2.8.x and no MakeTarget is showing in the properties, then I tried this repo and the addon doesnt install atall, any ideas? thanks

**Comment by joepal1976** [comment]
The maketarget that came with alpha 3 is for blender 2.79.

What happens when you try to install this repo? Do you get any warning or error message or console output?

**Comment by mandelmonkey** [comment]
Thanks for the reply, here is the console log
```
Read prefs: C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Loading MH community plug-in v 0.4
Loading sync plug-in
sync plug-in loaded
Loading kinect Sensor plug-in
kinect Sensor plug-in loaded
MH community plug-in load complete
Warning: class AnimationProps contains a property which should be an annotation!
C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MH_Community\kinect_sensor\kinect_ui.py:19
    assign as a type annotation: AnimationProps.id
    assign as a type annotation: AnimationProps.name
Loading makeclothes v 1.1.0
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\makeclothes\__init__.py", line 67, in <module>
    from maketarget.utils import drawFileCheck
ModuleNotFoundError: No module named 'maketarget.utils'
Loading MHX2 importer-runtime v 0.30
Loading MHX2 armature
build loaded
MHX2 armature loaded
shaders.py
MHX2 successfully (re)loaded
module changed on disk: 'C:\\Program Files\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\maketarget\\__init__.py' reloading...
Modules Installed () from 'C:\\Users\\Chris\\Downloads\\community-plugins-maketarget-master.zip' into 'C:\\Users\\Chris\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
```

**Comment by joepal1976** [comment]
The problem here is a clash with the old makeclothes/maketarget. You can't have both installed at the same time. 

I'm aware that this is not obvious: but the old makeclothes have a hard dependency on the old maketarget. It here tries to access a module in maketarget, something which won't work since the new maketarget is entirely different. 

From what I can see, the installation of maketarget went well in itself though.

My suggestion is to uninstall and remove all traces of makeclothes and maketarget and then try to reinstall the maketarget that comes from downloading this repo as a zip. 

Having done so, you should get a "maketarget 2" tab on the N shelf.

**Comment by Aranuvir** [comment]
I think we can close this topic.
