### ISSUE TITLE
Illogical application of control over attached geometry (possible user error/lack of knowledge)

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/community-plugins-maketarget#8]
There seems to be no rhyme or reason as to whether the shapekeys created will affect connected geometry once back in MakeHuman when using MakeTarget2, such as eyelashes and eyebrows.

There is a distinct possiblility that this is user error on my end.

Some of the shapekeys i make (I always use the same methods) will not move the eyelashes or eyebrows once back in makehuman, while others will. also, some of the shapekeys/targets i make will affect one set of eyelashes, but not another.
I cannot see any logical reason why this occurs. any insight is appreciated.

Thank you

**Comment by joepal1976** [comment]
Your targets need to also modify the helper geometry if you want things like eyebrows or hair to be affected (generally speaking). This will not be done automatically. 

The reason why it sometimes work and sometimes doesn't, is that a MHCLO asset (such as an eyebrow) might be matched against a mix of helper vertices and body vertices. In this case, a target affecting only body vertices would shift only that part of the particular MHCLO asset.

So: please test making a target that affects all relevant vertices, including the helper geometry and report back if it still causes strange behavior. If it works, simply close this issue.

The switch for showing/hiding helper geometry is a mask modifier on the body mesh.

**Comment by Hunanbean** [comment]
Ok, thanks for the information, and that makes perfect sense. I think perhaps there may be another issue i am experiencing. I will try to describe.
Using the MakeTarget2 settings, i import a model into Blender. (2.83lts or 2.90 release)
I unhide the helper geometry by click the display icon, and pressing the toggle. This allows me to see both the helper geometry and the model at the same time.
I press Create Target within MakeTarget2 panel
I move any of the helper geometry. It does not move the model in blender. 
I move base model vertices, it does show in Blender, and also does export a shape key that moves vertices in MakeHuman.
I move a combination of vertices of Body and Helper. Only Body seems to have an effect. for example, if i move the cube helpers that i think should affect the chin dropping, or the ones to open/close eyelids, they seem to have no effect.
also, once a shapekey is created, any subsequent changes do not seem to apply.

To further eliminate the probability of user error or lack of comprehension, is there an updated video tutorial, using MakeTarget2, MakeHuman 1.2.*, and Blender 2.8+? I am familiar with the resources VScorpionC has created, but i seem to be having different issues.

side question, is moving the helper geometry in blender supposed to also move Body in blender or just when it gets the target back into MakeHuman?

Thank you

**Comment by black-punkduck** [comment]
It is like this: the target you create in blender is simply nothing else than a blender shape key. At least in my version  it worked well for the helpers, because short time ago I corrected the hair helper for some targets.  So for blender it is nothing special.

The effect will be visible in MakeHuman. Compared to blender, which internally creates a second table of all(!) vertex coordinates, MakeHuman will get only the vertices which are changed with this shape-key. 

You can even check this, when you compare the numbers of the vertices in the resulting file with the table of this documentation:

[documentation basemesh](http://www.makehumancommunity.org/wiki/Documentation:Basemesh)

The result will normally have an effect, if you use some of the clothes modeled on the helper (most of the long dresses are modeled on helper). If you change the cubes ... nothing will happen. Internally the bones of the skeleton will start and end at a different position (see documentation above). But the character will not change because that is a new rest position now! If you then rotate a bone it might give unpredictable results.

**Comment by Hunanbean** [comment]
Ok, thank you both for all of the information. I think i am going to chalk this up to my lack of experience, and will continue working with it.
